### PR TITLE
Fix flakey aktualizr_kill test

### PR DESCRIPTION
**Pull request by cajun-rat**
This was introduced by commit #4c1c3f04 "Don't EXIT_SUCCESS if
Aktualizr::RunForever() throws an exception", which changed the logging output
when Aktualizr exits with an error. Generalizing the log message we look for
catches both arms of the branch.

Signed-off-by: Phil Wise <phil@phil-wise.com>

### CODE REVIEW

**Comment by pattivacek** [comment]
Unfortunately, it's still failing. :(

**Comment by cajun-rat** [comment]
> Unfortunately, it's still failing. :(

Gah!  Works on My Machine™.  I'll extend the test to print out what is going on when it fails to find the expected messages.

**Comment by cajun-rat** [comment]
Now the test failures are:

```
	  5 - test_crypto (Failed)
	  7 - test_keymanager (Failed)
```

I managed to typo the previous fix. I'd made a 1 character change to check that the test was actually functional and not passing regardless of what Aktualizr was doing, then left it in on the version I committed. My fault for writing the fix on the train on Friday night :)

`ctest -j8 --output-on-failure -R test_aktualizr_kill --repeat until-fail:10` is happy now. On my machine at least :^)

**Comment by pattivacek** [comment]
> I managed to typo the previous fix. I'd made a 1 character change to check that the test was actually functional and not passing regardless of what Aktualizr was doing, then left it in on the version I committed. My fault for writing the fix on the train on Friday night :)

Ha! No worries.

> `ctest -j8 --output-on-failure -R test_aktualizr_kill --repeat until-fail:10` is happy now. On my machine at least :^)

Works for me, too, and CI seems happy! Thank you!

**Pull request merged**
