### PR TITLE
Remove BUILD_DEB option

### PR DESCRIPTION
**Pull request by cajun-rat**
This feature allows building a Debian package that can run on a desktop machine as a kind of simulation mode. I'm not aware of anyone using this: real usages build using Yocto or run locally in development. Remove this feature.

### CODE REVIEW

**Comment by leonheldattoradex** [comment]
We maintain a Debian package here https://github.com/torizon/aktualizr-deb (for torizon-aktualizr, but it's pretty much the same thing). Should anyone need it, it should be trivial to make it point to the upstream repo instead.

**Comment by cajun-rat** [comment]
I wasn't aware of that--if people are using it then how about bringing that upstream? The delta looks pretty minimal

**Comment by charles2910** [comment]
I think all the packaging changes are self-contained in the  `debian/` dir

**Comment by cajun-rat** [comment]
Are you using the Debian packing tooling rather than [cpack](https://cmake.org/cmake/help/book/mastering-cmake/chapter/Packaging%20With%20CPack.html) on your branch @leonheldattoradex?  If so, then I'm even more keen to nuke the stuff that is using `BUILD_DEB` At least then we have one maintained solution, even if it isn't upstream yet :)

**Review by mike-sul — APPROVED** [review]

**Comment by leonheldattoradex** [comment]
> Are you using the Debian packing tooling rather

Yes, we have a custom pipeline that uses the usual tools[0]. One can just `sbuild`, `debuild` or else and it works, although we're moving to the more official Salsa CI GitLab pipeline [1] as soon as we have our public instance up.


[0] https://github.com/torizon/torizon-deb-ci
[1] https://salsa.debian.org/salsa-ci-team/pipeline

I'll setup a build for the "non-Torizon" Aktualizr and create an official Debian package on the upstream, what you think?

**Comment by rborn-tx** [comment]
I imagine the existing solution using `cpack` is something that still works, right? And it was being removed because we thought no one was using it.

@cajun-rat Now that we know someone is, shouldn't we keep it? Or does it add some relevant maintenance effort?

Replacing the `cpack` solution with the Debian tools seems odd to me simply because `cpack` is integrated with CMake which I imagine makes it easier to maintain compared with the Debian tools.

@leonheldattoradex Or are there good reasons for using the Debian tools rather than `cpack`?

**Comment by cajun-rat** [comment]
> I imagine the existing solution using `cpack` is something that still works, right? 

It depends what you mean by 'works' :)  Running `cpack`generates a couple of .deb files, but I don't think anyone has validated that they are functional.

> And it was being removed because we thought no one was using it.
> @cajun-rat Now that we know someone is, shouldn't we keep it? Or does it add some relevant maintenance effort?
> 
> Replacing the `cpack` solution with the Debian tools seems odd to me simply because `cpack` is integrated with CMake which I imagine makes it easier to maintain compared with the Debian tools.
> 
> @leonheldattoradex Or are there good reasons for using the Debian tools rather than `cpack`?

The current situation as I see it is we have 2 independent implementations of similar functionality:

* Upstream uses cpack, but no-one uses it
* @leonheldattoradex maintains a downstream version that uses the Debian tools

Since @leonheldattoradex is the active maintainer here, I'll let them pick the implementation approach. I recall the Debian community prefers to use Debian tooling to build packages rather than those built into other tools, so while cpack is good for people who are doing 'cmake' it is worse for people doing 'Debian'. 

I think there are two approaches from where we are today:

* Nuke BUILD_DEB now, and incrementally bring [torizon-deb-ci](https://github.com/torizon/torizon-deb-ci) closer to upstream.
* Migrate [torizon-deb-ci](https://github.com/torizon/torizon-deb-ci) to cpack and upstream it now instead of this PR.

My preference would be for the first, but if someone wants to work on the latter I'm happy to help!

**Comment by rborn-tx** [comment]
> It depends what you mean by 'works' :) Running `cpack`generates a couple of .deb files, but I don't think anyone has validated that they are functional.
> [...]
> I recall the Debian community prefers to use Debian tooling to build packages rather than those built into other tools, so while cpack is good for people who are doing 'cmake' it is worse for people doing 'Debian'.

Ok, considering the above, it seems reasonable to nuke `BUILD_DEB`. Approving the PR.

**Review by rborn-tx — APPROVED** [review]

**Comment by cajun-rat** [comment]
Cool. I'll merge this now. Shout if I can help with the upstreamng bit!

**Pull request merged**
