### PR TITLE
Fix flaky tests

### PR DESCRIPTION
**Pull request by cajun-rat**
This might be the last 2. See https://github.com/uptane/aktualizr/issues/45

### CODE REVIEW

**Comment by pattivacek** [comment]
Thanks for fixing the rotation bug! I think that was actually affecting multiple tests, but the rotation one is the most susceptible.

For the redirect test, it looks to me like we should expect the update to fail in that case. We're limiting to 10 redirects with `CURLOPT_MAXREDIRS`, which is good. Instead of reverting the test, can we change it so that we expect it to fail?

What confuses me, though, is that it apparently succeeds sometimes. I mean, it succeeds in CI all the time. I fear the problem goes deeper, but I have no insight on it.

**Review by mike-sul — APPROVED** [review]
nice catch.

**Comment by mike-sul** [comment]
> I think we have to split `test_treehub_update_after_image_download_failure` into two to do that (one that expects success and one that expects failure) if I'm understanding the code correctly. I am a bit confused if multiple handlers really means that the test is running multiple times; it's kind of hard to sort that out.

`test_treehub_update_after_image_download_failure` runs a few times, once for each handler.
iirc, the goal of the test to verify whether an update eventually succeeds (retries) after an initial download failure cause by different reasons (hence different handlers). In the case of RedirectHandler, a download is supposed to fail cause it exceeds maximum allowed redirects, but the following download try (no any failure injection) should be successful.

I don't think that there is a need in another test for the `Expect success with <10 redirects, let's say 8.` since there is already such test - `test_customrepo_update_redirect`.

**Comment by pattivacek** [comment]
> `test_treehub_update_after_image_download_failure` runs a few times, once for each handler.
> iirc, the goal of the test to verify whether an update eventually succeeds (retries) after an initial download failure cause by different reasons (hence different handlers). In the case of RedirectHandler, a download is supposed to fail because it exceeds maximum allowed redirects, but the following download try (no any failure injection) should be successful.

Okay, great, thanks for jumping in! Do you have a suspicion why the test is flaky, though?

> I don't think that there is a need in another test for the `Expect success with <10 redirects, let's say 8.` since there is already such test - `test_customrepo_update_redirect`.

Good call, thanks!

**Comment by mike-sul** [comment]
> Do you have a suspicion why the test is flaky, though?

No, I'll check it out in the evening.

**Comment by mike-sul** [comment]
I don't know why `test_treehub_failure` is flaky, I couldn't reproduce it locally.

But, after looking closely into it, I believe that `RedirectHandler` is supposed to be commented because it actually doesn't test the scenario it supposed to test, which is "update must succeed on next update cycle after unsuccessful ostree download during the current update cycle". So, what it really does is just making sure that libostree->libcurl supports redirects (redirects happens internally within libcurl and the first update cycle is successful.

On another hand, this test might be useful in the future when ostree/libostree will allow configuring a maximum number of redirects at the libcurl it uses (as we do in the aktualizr's httpclient), in this case the test/handler can be enabled with `number_of_redirects=<MAX_OSTREE_CURL_REDIRECTS> + 1` and it will test the expected scenario.

BTW, it is kind of security issue, once an ostree server is compromised a hacker can setup a server that returns 301 eternally so aklite gets stuck at a download phase and won't be able to pick up a new update.

**Comment by mike-sul** [comment]
Just in case, `@with_aktualizr` fixture has `output_logs` param, so if to enable it `@with_aktualizr(start=False, run_mode='once', output_logs=True)` then a test will output aktualizr's logs.

**Comment by pattivacek** [comment]
Thanks for the clarification @mike-sul! Based on what you've said, I have an idea why it's failing sometimes but not always. The test first checks if the image is pending, then it retries and expects it to succeed. The test expects the 1000 redirects to force a failure, but in fact it does not, so if libaktualizr and libostree can sort them out before the 120 seconds of `wait_for_completion()` are up, then the test will fail, because it's expecting the update to be pending, not complete. If the 1000 redirects take long enough to process that it exceeds the timeout, but it gets sorted out in time for the second check, it will succeed.

Clearly this test doesn't do what I'd originally expected. It should be commented out again. However, I'd like to leave a more helpful comment based on your insight about curl redirect limitation support in libostree. I also don't like restoring the ticket reference to a Jira instance none of us have access to.

**Comment by mike-sul** [comment]
Interestingly that `CURLOPT(CURLOPT_MAXREDIRS, CURLOPTTYPE_LONG, 68),` is set in my local curl.h, so I wondering why it keeps making requests to the test ostree server on my setup. I tried 500000 redirects and the test fails because of timeout (120s) but libostree->libcurl never exited because it reached the redirect limit (68).

**Comment by pattivacek** [comment]
> Interestingly that `CURLOPT(CURLOPT_MAXREDIRS, CURLOPTTYPE_LONG, 68),` is set in my local curl.h, so I wondering why it keeps making requests to the test ostree server on my setup.

Are you sure that's actually getting used? According to https://curl.se/libcurl/c/CURLOPT_MAXREDIRS.html, the default is unlimited.

**Comment by mike-sul** [comment]
> Are you sure that's actually getting used? According to https://curl.se/libcurl/c/CURLOPT_MAXREDIRS.html, the default is unlimited.

You are right, I am mistaken, this is just the option declaration and 68 is just its order number :).

**Review by pattivacek — APPROVED** [review]
I'm going to add a small comment cleanup commit to https://github.com/uptane/aktualizr/pull/47, but this is good to go as is.

**Pull request merged**
