### PR TITLE
Test an update if metadata version is the same while their content have been changed

### PR DESCRIPTION
**Pull request by mike-sul**
Add a test that verify whether aktualizr can perform an update if
targets and corresponding snapshot and timestamp metadata are updated
while their version is the same.
This test is specifically dedicated for the recent fix to the imagerepo
functionality
https://github.com/uptane/aktualizr/commit/9d3ee3ae1b1c8a0d0739fbc29664efa05f57d57f

### CODE REVIEW

**Comment by mike-sul** [comment]
@pattivacek I am not sure whether I should add the change to `advancedtelematic/tuf-test-vectors` repo or `uptane/tuf-test-vectors`. Aktualizr refers to the former, so I pushed the change to it https://github.com/advancedtelematic/tuf-test-vectors/pull/77. Also, I am confused how your commit ended up in that PR.

**Comment by mike-sul** [comment]
If I rollback the fix, then the test yields the following error messages

```
Skipping Image repo Snapshot download; stored version is still current.
Skipping Image repo Targets download; stored version is still current.
1 new update found in both Director and Image repo metadata.
New updates found in stored Director metadata. Checking stored Image repo metadata...
Hash verification for Snapshot metadata failed
Failed to check Image repo metadata: Snapshot metadata hash verification failed
```

**Comment by pattivacek** [comment]
> I am not sure whether I should add the change to `advancedtelematic/tuf-test-vectors` repo or `uptane/tuf-test-vectors`. Aktualizr refers to the former, so I pushed the change to it [advancedtelematic/tuf-test-vectors#77](https://github.com/advancedtelematic/tuf-test-vectors/pull/77). Also, I am confused how your commit ended up in that PR.

See my comment in https://github.com/advancedtelematic/tuf-test-vectors/pull/77#pullrequestreview-937933552.

> If I rollback the fix, then the test yields the following error messages

Great, that seems to tell us that the test is working! It's unfortunate that the error message wasn't very helpful. It was sort of an edge case we were hoping to ignore, so I'm not too surprised there that it isn't very clear. At least it did reject the metadata as expected.

**Comment by pattivacek** [comment]
Does this need to get updated to point to the master branch instead of the now-merged branch?

**Comment by mike-sul** [comment]
> Does this need to get updated to point to the master branch instead of the now-merged branch?

I guess it has been already done?

**Comment by pattivacek** [comment]
> I guess it has been already done?

Haha, that's what I just did. :) I'm gonna merge now.

**Review by pattivacek — APPROVED** [review]
Strange things are happening with tuf-test-vectors, perhaps because I still haven't been able to make sense of why https://github.com/uptane/aktualizr/pull/73 is failing CI. Anyway, this looks fine and is good to go now.

**Pull request merged**
